name: Build backend on pull request

on:
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: backend
      run: npm install

    - name: Run linter
      working-directory: backend
      run: npm run lint

    - name: Test
      working-directory: backend
      run: npm test

    - name: Build project
      working-directory: backend
      run: npm run build